---
title: Call for Papers
---



We are pleased to invite **1500-word extended abstracts** for the 32nd Annual GISRUK Conference, to be held **9th -- 12th April 2024** at the University of Leeds. The deadline is ~~Monday 8th January 2024~~ **Friday 19th January 2024** and submission is via Oxford Abstracts ([submission link](https://app.oxfordabstracts.com/stages/6800/submitter)).

Work presented at GISRUK covers a range of methodological approaches and application areas. We are particularly interested in papers that align with the conference theme --  **GIS for public good: data, theory, policy** -- but  below is a non-exhaustive list of typical focuses:

*Data/Methods*

* Spatial statistics
* Agent-based models
* Open data and code
* Reproducibility and inference
* Uncertainty quantification and analysis
* Machine learning and AI
* Data visualization and communication


*Application areas*

* Transportation and land use
* Environment and sustainability
* Health, neighbourhoods and housing
* Crime analysis
* Labour markets and economic geography

Submitted abstracts will be assessed by **at least two members** from the GISRUK 2024 Scientific Committee.

**New**. We have agreed a Special Issue linked to the conference with [Environment & Planning B: Urban Data/Code](https://uk.sagepub.com/en-gb/eur/environment-and-planning-b-urban-analytics-and-city-science/journal203385#description). Details to follow, but we will be encouraging discrete Data/Code products that relate to the conference theme: *GIS for public good: data, theory, policy*. For information on the Urban Data/Code section of E&P B, see Arribas-Bel et al.'s (2021) [editorial](https://journals.sagepub.com/doi/full/10.1177/23998083211059670?_gl=1*1y72m9o*_ga*MTM3ODc1NzM1OS4xNjQyNzA4NjE5*_ga_60R758KFDG*MTcwMzE2MjMwMS40NC4wLjE3MDMxNjIzMDEuNjAuMC4w).

### Guidelines

* Submission is via Oxford Abstracts [submission link](https://app.oxfordabstracts.com/stages/6800/submitter).
* Submissions should be extended abstracts of no more than 1500 words.
* Abstracts must be prepared using one of these templates ([MS Word](../files/GISRUK2024_PaperTemplateSubmission.docx), [LaTeX](../files/GISRUK2024-LaTeX_template.zip), [Quarto](https://github.com/sdesabbata/quarto-gisruk)).
* **New**: Identify whether you would like your submission to be considered for the [GISRUK & OSGeo:UK GoFundGeo Award](/osgeo/).
* Authors should make efforts towards enabling reproducibility of their work, where possible. GISRUK do not produce specific guidance, but authors may wish to consult relevant documentation from organisations such as [AGILE](https://osf.io/numa5).
* Any queries can be directed to : [info@gisruk.org](mailto:info@gisruk.org).

### Key dates

* Paper submission deadline: ~~Monday 8th January 2024~~ Friday 19th January 2024
* Paper review notifications: ~~Monday 12th February 2024~~ Monday 19th February 2024
