---
title: "GISRUK 2024 : University of Leeds"
---

::: {.callout-important icon=true}

### Welcome and ECR Lunch

**Welcome**. We very much looking forward to seeing you in Leeds! Keep an eye out on this page as we post further updates in the next few days. See also a curated a list of [{{< fa solid link >}}recommended places](https://2024.gisruk.org/venue/#other-places) nearby for food / drink. 


<div class="inline"> <i class="fa-regular fa-bullhorn fa-beat-fade fa-xl" style="color:#b6545c; --fa-animation-duration: 2s; --fa-fade-opacity: 0.6;" ></i>  &nbsp;  **Welcome Lunch**. One update is that there is lunch today -- Wed 10th April -- on arrival. This is scheduled from c.1200.  </div>

<br>
**Best paper / poster prize**. As ever, there is voting for the [{{< fa solid link >}}Best Paper awards](https://forms.office.com/e/6nf8Ut36ZF). 


:::


---------

Welcome to the 32nd Annual GIS Research UK Conference. The conference will be hosted at University of Leeds on **9th -- 12th April 2024**.

GISRUK attracts international researchers and practitioners in GIS and related fields to share and discuss the latest advances in spatial computing and analysis. The work presented at GISRUK covers a range of methodological approaches and application areas, including: geographic data science, geocomputation, applied statistics, geography, health, urban and transport planning, crime science.

We welcome papers covering all aspects of GIS, both methodological and applied. There is also a theme for the 2024 conference --  **GIS for public good: data, theory, policy** -- around which keynotes and other activity will be structured.

See the [Call for papers](cfp/) for details on how to submit.

**New**. We have agreed a Special Issue linked to the conference with [Environment & Planning B: Urban Data/Code](https://uk.sagepub.com/en-gb/eur/environment-and-planning-b-urban-analytics-and-city-science/journal203385#description). 
Details can be found [here](si/).
We encourage discrete Data/Code products that relate to the conference theme: *GIS for public good: data, theory, policy*. 
For information on the Urban Data/Code section, see Arribas-Bel et al.'s (2021) [editorial](https://journals.sagepub.com/doi/full/10.1177/23998083211059670?_gl=1*1y72m9o*_ga*MTM3ODc1NzM1OS4xNjQyNzA4NjE5*_ga_60R758KFDG*MTcwMzE2MjMwMS40NC4wLjE3MDMxNjIzMDEuNjAuMC4w).

## Key Dates

* Paper submission deadline: ~~Monday 8th January 2024~~ Friday 19th January 2024
* Paper review notifications: ~~Monday 12th February 2024~~ Monday 19th February 2024
* Registration opens: February 2024
* ECR workshops: 9th-10th April 2024
* Conference: 10th-12th April 2024
