---
title: SI with E&P B Urban Data/Code
---

For over 30 years the annual GISRUK conference has showcased discrete research projects that contribute new theories, methods and insights to a very wide set of spatial analysis problems and application areas.

A characteristic of most GISRUK submissions, even commentaries and perspective pieces (cf. Chris Brunsdon's 2023 keynote on Bayes, Ulam and Missingness), is that they are underpinned by some new and interesting dataset and/or computational technique. 
Many GISRUK authors make a habit of publishing their code and data via open platforms (Figshare, Dataverse, Github, CRAN, pypi). 
The importance of this activity -- open data and methods -- is nowadays taken-for-granted in the GISRUK community. 
However, mechanisms for incentivising and formalising it are perhaps less well-established. 
 
With [this Special Issue](https://journals.sagepub.com/page/epb/collections/special-issues), we invite GISRUK authors to document the code and/or data underpinning their work.
We encourage submissions featured either at the latest 2024 conference or those appearing in the recent past and certainly submissions that extend and expand upon early work presented at GISRUK.

Edited by Roger Beecham (School of Geography and Leeds Institute for Data Analytics, University of Leeds, [r.j.beecham@leeds.ac.uk](r.j.beecham@leeds.ac.uk)), Arjan Gosal, Nick Hood, Vikki Houlden, Will James, Rachel Oldroyd, Keiran Suchak (School of Geography, University of Leeds), Fran Pontin (Leeds Institute for Data Analytics and School of Geography, University of Leeds) and Jonny Huck (Department of Geography, University of Manchester).
