---
title: "Conference Programme"
---

```{r}
#| echo: false
#| warning: false
#| eval: false
library(gt)
library(gtExtras)
library(fontawesome)
library(ggtext)
```


<!-- ### Tuesday 9th April 2024 -->

```{r}
#| label: program-tues
#| echo: false
#| eval: false

day <- tibble::tibble(
  Type = c(rep("ECR Workshop",4), "ECR Social"),
  When = c(
    "1300-1330",
    "1330-1430",
    "1430-1500",
    "1500-1700",
    "1800-"
    ),
  What = c(
    "Welcome",
    "Event 1",
    "Tea/Coffe",
    "Event 2",
    "Dinner / social"
    ),
  Where = c(
    "Denim/Wool",
    "Denim/Wool",
    "Merchant's Hall",
    "Denim/Wool",
    "Leeds City, TBC"
    )
)

# kbl(day, protect_latex = TRUE, escape=FALSE, warn=FALSE, padding=-1L) |>
#  row_spec(0, extra_css = "border-bottom: 1px solid;") |>
#  pack_rows("ECR workshop : Wool/Denim?", 1,4, bold=FALSE, label_row_css = "border-bottom: 0px solid;") |>
#  pack_rows("ECR Social : Venue TBC", 5, 5,bold=FALSE, label_row_css = "border-bottom: 0px solid;") |>
#  column_spec(1, width = "10em", extra_css = "font-family:  Monospace", color="#56585D")

sysfonts::font_add(family = "Font Awesome 6 Regular",
                   regular = "path-to-font/Font-Awesome-6-Regular-400.otf")
showtext::showtext_auto()

day |>
gt(groupname_col = "Type") |> 
  cols_align("left", Type) |>
  gt_add_divider(
    What, "left", 
    weight = px(1), color = "#d3d3d3"
    ) |> 
    gt_theme_nytimes() |>
    tab_options(data_row.padding = px(.8),
              table.font.size = px(20),
              column_labels.font.size = px(22), table.align="left", row_group.font.size = px(18)) 

```

<!-- ### Wednesday 10th April 2024 -->

```{r}
#| label: program-wed
#| echo: false
#| eval: false

day <- tibble::tibble(
  Type = c(rep("ECR Workshop",4), "ECR Social"),
  Time = c(
    "0930-1045",
    "1045-1115",
    "1115-1230",
    "1230-1330",
    "1330-1400"
    "1400-1500",
    "1500-1530",
    "1430-1500",
    "1530-1630",
    "1730-"
    ),
  Activity = c(
    "Welcome, RB&FP",
    "Event 1",
    "Tea/Coffe",
    "Event 2",
    "Dinner / social"
    )
  Where = c(
    "Denim/Wool",
    "Denim/Wool",
    "Merchant's Hall",
    "Denim/Wool",
    "Leeds City -- TBC"
    )
)

day |>
gt(groupname_col = "Type") |> 
  cols_align("left", Type) |>
  gt_add_divider(
    Activity, "left", 
    weight = px(1), color = "#d3d3d3"
    ) |> 
    gt_theme_nytimes() |>
    tab_options(data_row.padding = px(.8),
              table.font.size = px(20),
              column_labels.font.size = px(22), table.align="left", row_group.font.size = px(18)) 

```